# Sample buildspec for checking PR in codecommit
# Allow codebuild role to create EKS resources
version: 0.2
env:
  variables:
    TERRAFORM_VERSION: "0.14.11"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  build:
    commands:
      - echo "Running terraform plan"
      - terraform plan -out=tf.plan
      # Add check plan or separate out build
      - terraform apply "tf.plan"
