# Default values for notejam-express.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will be the name of the node to create
nodeName: notejam

metadata:
  # This is the namespace in which the app will be deployed
  namespace: notejam
  # This is the env variable to be passed
  env: development


# The number of replicas the node will have
replicaCount: 1

# Add any deployment annotations
deployment:
  #   annotations:
  #     key: "value"
  annotations: {}

# This will group the values of the expressapp
expressapp:
  #This defines the service type of the node
  serviceType: ClusterIP
  # The image that will be pulled from docker url
  image: sownak/notejam:latest
  # The pull policy
  pullPolicy: Always
  # The node ports to be exposed
  nodePorts:
      port: 3000
      targetPort: 3000
      name: tcp
proxy:
  #This will be the proxy/ingress provider.
  #Eg. provider: "ambassador"
  provider: ambassador
  #Eg. external_url_suffix: org1.blockchaincloudpoc.com
  external_url_suffix: app.bafevent.com

# Provide Volume details for database volume
storage:
  # Storageclass Name: gp2 is default in EKS
  storageclassname: gp2
  # Storage size
  storagesize: 1Gi
